---
resources:
- name: apps-movie-fun-code
  type: git
  source:
    uri: https://github.com/markus-wissmann/apps-movie-fun-code.git
    branch: markus-spring-boot

- name: deploy-movie-fun
  type: cf
  source:
    api: http://api.sys.pikes.pal.pivotal.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: wmarkus-pal
    space: sandbox
    skip_cert_check: true

jobs:
- name: deploy
  public: true
  plan:
  - get: apps-movie-fun-code
    trigger: true
  - task: package
    file: apps-movie-fun-code/src/ci/tasks/package.yml
  - put: deploy-movie-fun
    params:
      manifest: apps-movie-fun-code/manifest.yml
      path: package-output/apps-movie-fun-code.war

- name: smoke_test
  public: true
  plan:
  - get: apps-movie-fun-code
    trigger: true
    passed: [deploy]
  - task: smoke_test
    file: apps-movie-fun-code/src/ci/tasks/smoke-test.yml
    params:
      MOVIE_FUN_URL: http://apps-movie-fun-code-longish-midrib.apps.pikes.pal.pivotal.io
